@startuml
scale 2
package "host machine" {
    [browser]

    component "docker" {
        port p8000
        port p8001
        [api]
        [server]
        [web]
    }
}


browser <-- p8000
p8000 <--- web
browser --> p8001
p8001 --> server
server --> api
@enduml