version: "3.8"
services:
  web:
    image: sample-web-app:0.0.1
    build:
      context: ./web
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    networks:
      - sample-app-net
    depends_on:
      - server
  server:
    image: sample-server-app:0.0.1
    build:
      context: ./server
    ports:
      - "8001:8001"
    networks:
      - sample-app-net

networks:
  sample-app-net: